<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <UserSecretsId>4b5a1f53-e2bf-4e98-8aab-7a7ca54d9e1b</UserSecretsId>
  </PropertyGroup>
  
  <ItemGroup>
    <GraphQL Remove="Client\GetProducts.graphql" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.FeatureManagement.AspNetCore" />
    <PackageReference Include="MudBlazor" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" />
    <PackageReference Include="Humanizer.Core" />

    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="Serilog.Sinks.Seq" />
    <PackageReference Include="Serilog.Enrichers.Sensitive" />
    <PackageReference Include="Serilog.Enrichers.ExceptionData" />
    <PackageReference Include="Serilog.Enrichers.AspNetCore" />
    <PackageReference Include="Serilog.Enrichers.Context" />
    <PackageReference Include="Serilog.Enrichers.CorrelationId" />
    <PackageReference Include="Serilog.Enrichers.Environment" />
    <PackageReference Include="Serilog.Enrichers.Process" />
    <PackageReference Include="Serilog.Enrichers.Thread" />
    <PackageReference Include="Serilog.Exceptions" />
    <PackageReference Include="Serilog.Formatting.Compact" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ThumbezaTech.Leads.ClientLibrary\ThumbezaTech.Leads.ClientLibrary.csproj" />
  </ItemGroup>
</Project>